version: 2
jobs:
  build:
    working_directory: ~/dazl
    docker:
      - image: rappdw/docker-java-python
    resource_class: medium+
    steps:
      - run:
          name: Install poetry and jq
          command: |
            curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python && \
            source $HOME/.poetry/env && \
            pip install pipenv && \
            poetry config virtualenvs.in-project true && \
            curl -LO https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 && \
            chmod 755 jq-linux64 && \
            mv jq-linux64 /usr/bin/jq
      - checkout
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "python/poetry.lock" }}
      - run:
          command: |
            source $HOME/.poetry/env && \
            make -C python deps
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "python/poetry.lock" }}
          paths:
            - "python/.venv"
      - run:
          name: Python unit tests
          command: |
            source $HOME/.poetry/env && \
            make -C python test
      - run:
          name: Python integration tests
          command: |
            source $HOME/.poetry/env && \
            make -C python integration-test
      - run:
          name: Python packaging
          command: |
            source $HOME/.poetry/env && \
            make -C python package
      - run:
          name: Run Blackduck Detect
          command: |
            bash <(curl -s https://raw.githubusercontent.com/DACH-NY/security-blackduck/master/synopsys-detect) ci-build digitalasset_dazl master --logging.level.com.synopsys.integration=DEBUG --detect.python.python3=true
      - store_test_results:
          path: python/test-results
      - persist_to_workspace:
          root: ~/dazl
          paths:
            - python/dist

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: blackduck
